name: CI with C/C++ Exotic Action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        #os: [windows-latest]
        platform: [x86, x64]
        compiler: [gnu]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Exotic Libraries
        uses: exoticlibraries/exotic-action@master
        with:
          run-cester-regression: false
        
      - name: Run Regression
        uses: exoticlibraries/exotic-action@master
        with:
          download-exotic-libraries: false
          test-folders: |
            test/
            tests/
          test-exclude-file-pattern: |
            test_shared_data.c
            mock+
          test-exclude-file-pattern-x86: |
            kdjksjksjd
          test-exclude-file-pattern-x64: |
            kdjksjksjd
        
