name: CI with C/C++ Exotic Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [windows-2002]
        platform: [x86, x64]
        compiler: [gcc, clang, tcc, msvc]
        #compiler: [gcc]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Exotic Libraries
        uses: exoticlibraries/exotic-action@1d4a5a5f1a2d234834996d74ecf2d909a0a2b697
        with:
          run-regression: false
          selected-exotic-libraries: |
            libcester@main
            libxtd@dev
            libmetaref@dev
            libcline@dev
        
      - name: Run Regression
        uses: exoticlibraries/exotic-action@1d4a5a5f1a2d234834996d74ecf2d909a0a2b697
        with:
          download-exotic-libraries: false
          run-regression: true
          test-folder-recursive: true
          test-folders: |
            test/
            test_2/
            tests/
          test-file-pattern: |
            nocester+
            test_+
          test-exclude-file-pattern: |
            test_assert_double_float+
            test_segfault+
            mock+
          test-exclude-file-pattern-gnu: |
            test_tap_output+
            nocester+
          test-exclude-file-pattern-gcc: |
            test_tap_output+
            nocester+
          test-exclude-file-pattern-clang: |
            test_tap_output+
            nocester+
          test-exclude-file-pattern-tcc: |
            test_tap_output+
            nocester+
          test-exclude-file-pattern-msvc: |
            test_tap_output+
            nocester+
          compiler-options-for-tests: |
            -O2 
            -Wall 
            -Wpointer-arith 
            -Wmissing-noreturn

        
