name: CI with C/C++ Exotic Action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        #os: [windows-latest]
        platform: [x64]
        compiler: [gnu]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Exotic Libraries
        uses: exoticlibraries/exotic-action@master
        with:
          run-regression: false
        
      - name: Run Regression
        uses: exoticlibraries/exotic-action@master
        with:
          download-exotic-libraries: false
          run-regression: true
          test-folder-recursive: true
          test-folders: |
            test/
            test_2/
            tests/
          test-file-pattern: |
            nocester+
            test_+
          test-exclude-file-pattern: |
            test_assert_double_float+
            test_segfault+
          compiler-options-for-tests: |
            -O2 
            -Wall 
            -Wpointer-arith 
            -Wmissing-noreturn
        
