name: CI with C/C++ Exotic Action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        #os: [windows-latest]
        platform: [x64]
        compiler: [gnu]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Exotic Libraries
        uses: exoticlibraries/exotic-action@b9d89ba6d5e47a0f1475e69212d147749e71f589
        with:
          run-regression: false
        
      - name: Run Regression
        uses: exoticlibraries/exotic-action@master
        with:
          download-exotic-libraries: false
          run-regression: true
          test-folders: |
            test/
            tests/
          test-exclude-file-pattern: |
            mock+
        
