name: CI with Cester

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        platform: [x64]
        compiler: [gnu]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      #- name: Download cester
      #  run: wget -O cester.h https://raw.githubusercontent.com/exoticlibraries/libcester/master/include/exotic/cester.h -q
        
      - name: Download cester
        run: "sudo bash <(curl -s https://exoticlibraries.github.io/libcester/cester.sh)"
        
      - name: Run tests
        run: |
          gcc test/test_no_assert.c -I. -o out; ./out
          gcc test/test_no_main.c -I. -o out; ./out
          gcc test/test_no_time.c -I. -o out; ./out
        
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
